# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApexProxy < Formula
  desc "Apex Proxy"
  homepage "https://reefassistant.com"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/reefassistant/apex-proxy/releases/download/v1.0.0/apex-proxy_1.0.0_darwin_arm64.tar.gz"
      sha256 "bd2d09d728734dacba19c2738a4af4fc503b947a83b40e521a250c50d8d4682f"

      def install
        bin.install "apex-proxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reefassistant/apex-proxy/releases/download/v1.0.0/apex-proxy_1.0.0_darwin_amd64.tar.gz"
      sha256 "e7d371777d88921e69b2660b95763651cae57a6f5a5fcb5ac96ea4c18846c6b2"

      def install
        bin.install "apex-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reefassistant/apex-proxy/releases/download/v1.0.0/apex-proxy_1.0.0_linux_arm32v7.tar.gz"
      sha256 "a8b62a9a1372838deb213e9e9fdd5106e3b46c206bd48356992a292e330b80ed"

      def install
        bin.install "apex-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reefassistant/apex-proxy/releases/download/v1.0.0/apex-proxy_1.0.0_linux_arm64.tar.gz"
      sha256 "4b35d35853c9e599d87b2381adedb226e6cc3b4bb95f7a8253cfb108cbb44f74"

      def install
        bin.install "apex-proxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reefassistant/apex-proxy/releases/download/v1.0.0/apex-proxy_1.0.0_linux_amd64.tar.gz"
      sha256 "e86d4f9bc9cd2fbf67c2abc65cb102a67b337b0b8063d58b1b76c314b3b4a186"

      def install
        bin.install "apex-proxy"
      end
    end
  end

  test do
    system "#{bin}/apex-proxy --help"
  end
end
